#
# SELinux policy module RPMs build
#
name: "Build RPMs to install compiled SELinux policy module"

on:
  release:
    types: [ published ]
  
  workflow_dispatch:
         
jobs:
  get_release_info:
    name: Get release info
    runs-on: ubuntu-latest

    outputs:
      upload_url: ${{ steps.get_release_url.outputs.upload_url }}
      version_number: ${{ steps.get_release_version.outputs.version }}
      release_number: ${{ steps.get_release_version.outputs.release }}

    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Get release
        id: get_release_url
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
       
      - name: Retrieve version and release numbers
        id: get_release_version
        run: |
          version_from_tag=$( echo "${{ github.ref_name }}" | sed -E 's,^v?([0-9]+\.[0-9]+\.[0-9]+).*$,\1,' )
          release_from_tag=$( echo "${{ github.ref_name }}" | sed -E 's,^v?[0-9]+\.[0-9]+\.[0-9]+(-([0-9]+))?.*$,\2,' )
          [ -z "${release_from_tag}" ] && release_from_tag=0
          echo "::set-output name=version::${version_from_tag}"
          echo "::set-output name=release::${release_from_tag}"
  
  build_RPMs:
    name: Build RPMs and upload them to release
    needs: get_release_info
    uses: Laurent-Gaillard/selinux_build_modules/.github/workflows/generic_semodule_build.yml@main
    with:
      spec_file_location: rpm/
      selinux_files_location: se_module/
      release_upload_url: ${{ needs.get_release_info.outputs.upload_url }}
      provided_version: ${{ needs.get_release_info.outputs.version_number }}
      provided_release: ${{ needs.get_release_info.outputs.release_number }}
      
